app:
  github:
    token: "${GITHUB_TOKEN}"
    base-url: "https://api.github.com"
    connection-timeout: 10s
    read-timeout: 30s
    max-retries: 3
    retry-delay: 1s
  stackoverflow:
    base-url: "https://api.stackexchange.com/2.3"
    connection-timeout: 10s
    read-timeout: 30s
    max-retries: 3
    retry-delay: 1s
    api:
      key: "${STACKOVERFLOW_KEY}"
      access-token: "${STACKOVERFLOW_TOKEN}"
  scheduling:
    batch-size: 100
  app:
    access-type: "SQL"
    bot-url: "http://localhost:8080"
    message-transport: KAFKA


kafka:
  bootstrap-servers: localhost:9092
  topics:
    updates: link-updates
    dlq: link-updates-dlq

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/scrapper
    username: postgres
    password: 1097111234
    driver-class-name: org.postgresql.Driver
  application:
    name: Scrapper
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 8081

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
