app:
  telegram-token: ${TELEGRAM_TOKEN} # env variable
  scrapper-url: http://localhost:8081
  message-transport: KAFKA

spring:
  application:
    name: Bot
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  cache:
      type: redis
  data:
    redis:
      host: localhost
      port: 6379

kafka:
  bootstrap-servers: localhost:9092
  topics:
    updates: link-updates
    dlq: link-updates-dlq

server:
  port: 8080

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui

resilience4j:
  timelimiter:
    instances:
      scrapperClient:
        timeout-duration: 2s

  circuitbreaker:
    instances:
      scrapperClient:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 1
        minimum-number-of-calls: 1
        failure-rate-threshold: 100
        permitted-number-of-calls-in-half-open-state: 1
        wait-duration-in-open-state: 1s

rate-limiting:
  enabled: true
  requests-per-minute: 60
